add_move_state: True
add_local_obs: False
add_distance_state: False
add_enemy_action_state: False
add_agent_id: False
add_visible_state: False
add_xy_state: False
use_state_agent: False
use_mustalive: True
add_center_xy: True
use_global_state: True
use_obs_instead_of_state: False
global_state_include_info: True
state_last_action: True
state_pathing_grid: True
state_terrain_height: True
state_timestep_number: True
stacked_frames: 1
use_stacked_frames: False
