add_move_state: False
add_local_obs: False
add_distance_state: False
add_enemy_action_state: False
add_agent_id: False
add_visible_state: False
add_xy_state: False
use_state_agent: True
use_mustalive: True
add_center_xy: True
use_global_state: False
use_obs_instead_of_state: False
global_state_include_info: False
state_last_action: True
state_pathing_grid: False
state_terrain_height: False
state_timestep_number: False
stacked_frames: 1
use_stacked_frames: False
