map_name: protoss_5_vs_5
# Options:
# protoss_5_vs_5
# protoss_10_vs_10
# protoss_10_vs_11
# protoss_20_vs_20
# protoss_20_vs_23
# terran_5_vs_5
# terran_10_vs_10
# terran_10_vs_11
# terran_20_vs_20
# terran_20_vs_23
# zerg_5_vs_5
# zerg_10_vs_10
# zerg_10_vs_11
# zerg_20_vs_20
# zerg_20_vs_23
